// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(LabAguaDbContext))]
    [Migration("20250422132753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Dominio.Entities.BaseEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAnalisis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaLLegada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Procedencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SitioExtraccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseEntities");

                    b.HasDiscriminator().HasValue("BaseEntities");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Dominio.Entities.Muestra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaExtraccion")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraExtraccion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<int>("LibroEntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("NombreMuestreador")
                        .HasColumnType("TEXT");

                    b.Property<string>("Procedencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMuestra")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LibroEntradaId");

                    b.ToTable("Muestras");
                });

            modelBuilder.Entity("Dominio.Entities.Bacteriologico", b =>
                {
                    b.HasBaseType("Dominio.Entities.BaseEntities");

                    b.Property<string>("ColiFecalesUfc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColiformesFecalesNmp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColiformesNmp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColoniasAgar")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuestraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.HasIndex("MuestraId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Bacteriologico");
                });

            modelBuilder.Entity("Dominio.Entities.FisicoQuimico", b =>
                {
                    b.HasBaseType("Dominio.Entities.BaseEntities");

                    b.Property<string>("Alcalinidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calcio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cloruros")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dbo5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dureza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Magnesio")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuestraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nitritos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ph")
                        .HasColumnType("TEXT");

                    b.Property<string>("Turbidez")
                        .HasColumnType("TEXT");

                    b.HasIndex("MuestraId")
                        .IsUnique();

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("MuestraId")
                                .HasColumnName("FisicoQuimico_MuestraId");
                        });

                    b.HasDiscriminator().HasValue("FisicoQuimico");
                });

            modelBuilder.Entity("Dominio.Entities.LibroDeEntrada", b =>
                {
                    b.HasBaseType("Dominio.Entities.BaseEntities");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Observaciones")
                                .HasColumnName("LibroDeEntrada_Observaciones");
                        });

                    b.HasDiscriminator().HasValue("LibroDeEntrada");
                });

            modelBuilder.Entity("Dominio.Entities.Muestra", b =>
                {
                    b.HasOne("Dominio.Entities.Cliente", "Cliente")
                        .WithMany("Muestras")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.LibroDeEntrada", "LibroEntrada")
                        .WithMany("Muestras")
                        .HasForeignKey("LibroEntradaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("LibroEntrada");
                });

            modelBuilder.Entity("Dominio.Entities.Bacteriologico", b =>
                {
                    b.HasOne("Dominio.Entities.Muestra", "Muestra")
                        .WithOne("Bacteriologia")
                        .HasForeignKey("Dominio.Entities.Bacteriologico", "MuestraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("Dominio.Entities.FisicoQuimico", b =>
                {
                    b.HasOne("Dominio.Entities.Muestra", "Muestra")
                        .WithOne("FisicoQuimico")
                        .HasForeignKey("Dominio.Entities.FisicoQuimico", "MuestraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("Dominio.Entities.Cliente", b =>
                {
                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("Dominio.Entities.Muestra", b =>
                {
                    b.Navigation("Bacteriologia");

                    b.Navigation("FisicoQuimico");
                });

            modelBuilder.Entity("Dominio.Entities.LibroDeEntrada", b =>
                {
                    b.Navigation("Muestras");
                });
#pragma warning restore 612, 618
        }
    }
}
